-- MySQL Script generated by MySQL Workbench
-- Sat Apr 13 13:01:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taller_db` ;

-- -----------------------------------------------------
-- Schema taller_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller_db` DEFAULT CHARACTER SET utf8 ;
USE `taller_db` ;

-- -----------------------------------------------------
-- Table `taller_db`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`vehiculo` (
  `idvehiculo` INT NOT NULL AUTO_INCREMENT,
  `numero_matricula` VARCHAR(45) NOT NULL,
  `pais_matricula` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`idvehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`cliente` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `numero_identificacion` VARCHAR(45) NOT NULL,
  `numero_celular` VARCHAR(45) NULL,
  `cuenta_correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`orden_de_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`orden_de_trabajo` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`orden_de_trabajo` (
  `idorden_de_trabajo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `idvehiculo` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idorden_de_trabajo`),
  INDEX `fk_orden_de_trabajo_vehiculo_idx` (`idvehiculo` ASC) VISIBLE,
  INDEX `fk_orden_de_trabajo_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_orden_de_trabajo_vehiculo`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `taller_db`.`vehiculo` (`idvehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_de_trabajo_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `taller_db`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`mecanico` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`mecanico` (
  `idmecanico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `numero_identificacion` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NULL,
  `numero_celular` VARCHAR(45) NULL,
  `cuenta_correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idmecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`mano_de_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`mano_de_obra` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`mano_de_obra` (
  `idmano_de_obra` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `horas_trabajadas` FLOAT NOT NULL,
  `costo_por_hora` FLOAT NOT NULL,
  `total` FLOAT NULL,
  `idorden_de_trabajo` INT NOT NULL,
  `idmecanico` INT NOT NULL,
  PRIMARY KEY (`idmano_de_obra`),
  INDEX `fk_mano_de_obra_orden_de_trabajo1_idx` (`idorden_de_trabajo` ASC) VISIBLE,
  INDEX `fk_mano_de_obra_mecanico1_idx` (`idmecanico` ASC) VISIBLE,
  CONSTRAINT `fk_mano_de_obra_orden_de_trabajo1`
    FOREIGN KEY (`idorden_de_trabajo`)
    REFERENCES `taller_db`.`orden_de_trabajo` (`idorden_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mano_de_obra_mecanico1`
    FOREIGN KEY (`idmecanico`)
    REFERENCES `taller_db`.`mecanico` (`idmecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`articulo` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo_unitario` FLOAT NOT NULL,
  `tipo_articulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idarticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_db`.`materiales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_db`.`materiales` ;

CREATE TABLE IF NOT EXISTS `taller_db`.`materiales` (
  `idmateriales` INT NOT NULL AUTO_INCREMENT,
  `costo_unitario` FLOAT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `total` FLOAT NULL,
  `idorden_de_trabajo` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  PRIMARY KEY (`idmateriales`),
  INDEX `fk_materiales_orden_de_trabajo1_idx` (`idorden_de_trabajo` ASC) VISIBLE,
  INDEX `fk_materiales_articulo1_idx` (`idarticulo` ASC) VISIBLE,
  CONSTRAINT `fk_materiales_orden_de_trabajo1`
    FOREIGN KEY (`idorden_de_trabajo`)
    REFERENCES `taller_db`.`orden_de_trabajo` (`idorden_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materiales_articulo1`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `taller_db`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
