-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 13:20:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_dw
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taller_dw` ;

-- -----------------------------------------------------
-- Schema taller_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller_dw` DEFAULT CHARACTER SET utf8 ;
USE `taller_dw` ;

-- -----------------------------------------------------
-- Table `taller_dw`.`dimension_vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_dw`.`dimension_vehiculo` ;

CREATE TABLE IF NOT EXISTS `taller_dw`.`dimension_vehiculo` (
  `idvehiculo` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_dw`.`echo_orden_de_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_dw`.`echo_orden_de_trabajo` ;

CREATE TABLE IF NOT EXISTS `taller_dw`.`echo_orden_de_trabajo` (
  `idorden_de_trabajo` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `costo_total` FLOAT NULL,
  `costo_mano_obra` FLOAT NULL,
  `costo_materiales` FLOAT NULL,
  `dia_fecha_creacion` INT NULL,
  `mes_fecha_creacion` INT NULL,
  `año_fecha_creacion` INT NULL,
  `idvehiculo` INT NOT NULL,
  PRIMARY KEY (`idorden_de_trabajo`),
  INDEX `fk_echo_orden_de_trabajo_dimension_vehiculo1_idx` (`idvehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_echo_orden_de_trabajo_dimension_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `taller_dw`.`dimension_vehiculo` (`idvehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_dw`.`dimension_mano_de_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_dw`.`dimension_mano_de_obra` ;

CREATE TABLE IF NOT EXISTS `taller_dw`.`dimension_mano_de_obra` (
  `idmano_de_obra` INT NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `horas_trabajadas` FLOAT NULL,
  `costo_por_hora` FLOAT NULL,
  `total` FLOAT NULL,
  `idorden_de_trabajo` INT NOT NULL,
  PRIMARY KEY (`idmano_de_obra`),
  INDEX `fk_dimension_mecanico_echo_orden_de_trabajo_idx` (`idorden_de_trabajo` ASC) VISIBLE,
  CONSTRAINT `fk_dimension_mecanico_echo_orden_de_trabajo`
    FOREIGN KEY (`idorden_de_trabajo`)
    REFERENCES `taller_dw`.`echo_orden_de_trabajo` (`idorden_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_dw`.`dimension_materiales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_dw`.`dimension_materiales` ;

CREATE TABLE IF NOT EXISTS `taller_dw`.`dimension_materiales` (
  `idmateriales` INT NOT NULL,
  `descripcion_articulo` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `costo_unitario` FLOAT NULL,
  `total` FLOAT NULL,
  `idorden_de_trabajo` INT NOT NULL,
  PRIMARY KEY (`idmateriales`),
  INDEX `fk_dimension_materiales_echo_orden_de_trabajo1_idx` (`idorden_de_trabajo` ASC) VISIBLE,
  CONSTRAINT `fk_dimension_materiales_echo_orden_de_trabajo1`
    FOREIGN KEY (`idorden_de_trabajo`)
    REFERENCES `taller_dw`.`echo_orden_de_trabajo` (`idorden_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
